# **Dictionary**

Dictionaries are used to store data values in key:value pairs.

A dictionary is a collection which is ordered*, changeable and do not allow duplicates.

In [ ]:
dic2 = {"a":1, "a": 2 , "b" :2}
print(dic2)

{'a': 2, 'b': 2}
{'a': 2, 'b': 2}

In [ ]:
dic2 = {"a":1, "b":2, "c" :2}
dic2

{'a': 1, 'b': 2, 'c': 2}

In [ ]:
def fuc1(d):
  d['first']= [1,2,3]

dic = {'first': {1,1},
       'Second': {2:"a"}}

print(dic)
fuc1(dic)
print(dic)

{'first': {1}, 'Second': {2: 'a'}}
{'first': [1, 2, 3], 'Second': {2: 'a'}}

In [ ]:
dic = {'first': 1, 'Second': 2 , "Third": 3}
dic

{'first': 1, 'Second': 2, 'Third': 3}

In [ ]:
dic = {'first': 1, 'Second': 2 , "Third": 3}
for  i in dic:
  print(i)

first
Second
Third

In [ ]:
dic = {'first': 1, 'Second': 2 , "Third": 3}
for x in dic:
  print(dic[x])

1
2
3

In [ ]:
dic = {'first': 1, 'Second': 2 , "Third": 3}
for x in dic.values():
  print(x)

1
2
3

In [ ]:
dic ={'first': 1, 'Second': 2, 'Third':3}
print(dic)
dic['fourth']= 4
print(dic)

{'first': 1, 'Second': 2, 'Third': 3}
{'first': 1, 'Second': 2, 'Third': 3, 'fourth': 4}

In [ ]:
dic ={'first': 1, 'Second': 2, 'Third':3}
print(dic)
dic['Third']= 4
print(dic)

{'first': 1, 'Second': 2, 'Third': 3}
{'first': 1, 'Second': 2, 'Third': 4}

# **POP Function**

In [ ]:
dic = {'first': 1, 'Second': 2, 'Third': 3}
print(dic)
dic.pop('first')
print(dic)

{'first': 1, 'Second': 2, 'Third': 3}
{'Second': 2, 'Third': 3}

del

In [ ]:
dic = {'first': 1, 'Second': 2, 'Third': 3}
print(dic)
del dic['first']
print(dic)

{'first': 1, 'Second': 2, 'Third': 3}
{'Second': 2, 'Third': 3}

In [ ]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
x = thisdict["model"]
x

'Mustang'

In [ ]:
thisdict ={
    'Brand': 'ford',
    'model': 'Mustang',
    'year': 1964
}
thisdict.get('model')

'Mustang'

In [ ]:
dics = {
    'Name': 'Saad',
    'Age': 24,
    'Gender': 'Male'

}
x=dics.keys()
y = dics.values()
print(x)
print(y)

dict_keys(['Name', 'Age', 'Gender'])
dict_values(['Saad', 24, 'Male'])

# **Update Value**

In [ ]:
dct = {
    'Name': 'Ali',
    'age': 33,
    'College': 'Punjab College'

}
dct['age']= 29 # value update
dct

{'Name': 'Ali', 'age': 29, 'College': 'Punjab College'}

In [ ]:
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}

x = car.values()

print(x) #before the change

car["year"] = 2020

print(x) #after the change

dict_values(['Ford', 'Mustang', 1964])
dict_values(['Ford', 'Mustang', 2020])

# ** Add Dictionary Items**

thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict["color"] = "red"
print(thisdict)

In [ ]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict["color"] = "red"
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'red'}

# **Update Dictionary**

The update() method will update the dictionary with the items from a given argument. If the item does not exist, the item will be added.

The argument must be a dictionary, or an iterable object with key:value pairs.

In [ ]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict.update({"color": "red"})
thisdict

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'red'}

# **Pnadas Library**

Pandas is a Python library used for working with data sets.

It has functions for analyzing, cleaning, exploring, and manipulating data.

The name "Pandas" has a reference to both "Panel Data", and "Python Data Analysis" and was created by Wes McKinney in 2008.

# **What is a Series?**
A Pandas Series is like a column in a table.

It is a one-dimensional array holding data of any type.

In [ ]:
import pandas as pd
from pandas import Series, DataFrame

obj = Series([3, 7, -5, 3])
obj

0    3
1    7
2   -5
3    3
dtype: int64

In [ ]:
onjs =([4,6,2,6])
print(onjs)
print(onjs.index)

[4, 6, 2, 6]
<built-in method index of list object at 0x7b16432be940>

In [ ]:
oj3= Series({'d': 2, "a": 3, "c" :5})
print(oj3)

d    2
a    3
c    5
dtype: int64

In [ ]:
obj4 = obj(oj3>0)
print(obj4)

TypeError: 'Series' object is not callable

In [ ]:
sdata = {'Teax': 10, 'Ohio': 20, 'Oregon': 15, 'Utah': 18}
states= ['Teax', 'Ohio', 'Oregon', 'Utah']
obj5 = Series(sdata, index=states)
print(obj5)

Teax      10
Ohio      20
Oregon    15
Utah      18
dtype: int64

In [ ]:
sdata = {'Teaxs': 10, "Ohio": 20, 'Orgean': 15, 'Utah': 18}
states = ['Teaxs' , 'Ohion', 'Orgean', 'Utah']

obj4 = Series(sdata,index=states)
print(obj4)

Teaxs     10.0
Ohion      NaN
Orgean    15.0
Utah      18.0
dtype: float64

In [ ]:
sdata = {'Teaxs': 10, "Ohio": 20, 'Orgean': 15, 'Utah': 18}
states = ['CHa' , 'Ohio', 'Orgean', 'Utah']

obj4 = Series(sdata,index=states)
print(obj4)

CHa        NaN
Ohio      20.0
Orgean    15.0
Utah      18.0
dtype: float64

In [ ]:
sdata = {'Teax': 10, "Ohion" :20, "Oregon": 30, "Utah": 12}
states= ['Teax', 'Ohio', 'Oregon', 'Utah']
obj5 = Series(sdata, index=states)
print(obj5)

Teax      10.0
Ohio       NaN
Oregon    30.0
Utah      12.0
dtype: float64

In [ ]:
sdata = {'Teax': 10, "Ohion" :20, "Oregon": 30, "Utah": 12}
states= ['Teax', 'Ohio', 'Oregon', 'Utah']
obj5 = Series(sdata, index=states)
print(obj5.add(5))

Teax      15.0
Ohio       NaN
Oregon    35.0
Utah      17.0
dtype: float64

# **What is a DataFrame?**

A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

In [ ]:
data = {'orange': [3,2,4,5], 'apple': [0,3,7,2]}

df = DataFrame(data)
df

   orange  apple
0       3      0
1       2      3
2       4      7
3       5      2

In [ ]:
data = {'apple': [3,4,2,1], 'orange': [5,7,3,8]}

#change the index value
df = pd.DataFrame(data, index=['Ahmed', 'Ali', 'Asad', 'Usama'])
print(df)

       apple  orange
Ahmed      3       5
Ali        4       7
Asad       2       3
Usama      1       8

# **Locate Named Indexes**
Use the named index in the loc attribute to return the specified row(s).

In [ ]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df.loc["day2"])

calories    380
duration     40
Name: day2, dtype: int64

In [ ]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df.loc[[0, 1]])

   calories  duration
0       420        50
1       380        40

In [ ]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df)

# **Upload the data**

In [ ]:
df = pd.read_csv('/content/pakistan_population.csv')

In [ ]:
df.head()

,Year,Population,Yearly % Change,Yearly Change,Migrants (net),Median Age,Fertility Rate,Density (P/Km²),Urban Pop %,Urban Population,Country's Share of World Pop,World Population,Pakistan Global Rank
0,2020,220892340,2.00,4327022,-233379,22.8,3.55,287,35.1,77437729,2.83,7794798739,5
1,2019,216565318,2.04,4337032,-233379,22.0,3.73,281,34.9,75510639,2.81,7713468100,5
2,2018,212228286,2.08,4322077,-233379,22.0,3.73,275,34.7,73630430,2.78,7631091040,5
3,2017,207906209,2.10,4274856,-233379,22.0,3.73,270,34.5,71795700,2.75,7547858925,5
4,2016,203631353,2.11,4204389,-233379,22.0,3.73,264,34.4,70005271,2.73,7464022049,6

In [ ]:
df.tail()

,Year,Population,Yearly % Change,Yearly Change,Migrants (net),Median Age,Fertility Rate,Density (P/Km²),Urban Pop %,Urban Population,Country's Share of World Pop,World Population,Pakistan Global Rank
13,1975,66816877,2.82,1734963,-27621,18.6,6.6,87,26.3,17592808,1.64,4079480606,10
14,1970,58142060,2.69,1444817,-41996,19.3,6.6,75,24.8,14416426,1.57,3700437046,10
15,1965,50917975,2.51,1185857,-18654,19.9,6.6,66,23.5,11954323,1.52,3339583597,14
16,1960,44988690,2.13,900132,-3340,20.1,6.6,58,22.1,9926658,1.48,3034949748,14
17,1955,40488030,1.52,589131,-1651,20.1,6.6,53,19.7,7968418,1.46,2773019936,14

In [ ]:
df.isnull().sum()

Year                            0
Population                      0
Yearly % Change                 0
Yearly Change                   0
Migrants (net)                  0
Median Age                      0
Fertility Rate                  0
Density (P/Km²)                 0
Urban Pop %                     0
Urban Population                0
Country's Share of World Pop    0
World Population                0
Pakistan Global Rank            0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Year                          18 non-null     int64
 1   Population                    18 non-null     int64
 2   Yearly % Change               18 non-null     float64
 3   Yearly Change                 18 non-null     int64
 4   Migrants (net)                18 non-null     int64
 5   Median Age                    18 non-null     float64
 6   Fertility Rate                18 non-null     float64
 7   Density (P/Km²)               18 non-null     int64
 8   Urban Pop %                   18 non-null     float64
 9   Urban Population              18 non-null     int64
 10  Country's Share of World Pop  18 non-null     float64
 11  World Population              18 non-null     int64
 12  Pakistan Global Rank          18 non-null     int64
dtypes: float64(5), int64(8)
memory usage: 2.0 KB

In [ ]:
df.shape

(18, 13)

In [ ]:
#check dupicated value
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
dtype: bool

In [ ]:
#check duplicated row
df[df.duplicated()]

Empty DataFrame
Columns: [Year, Population, Yearly % Change, Yearly Change, Migrants (net), Median Age, Fertility Rate, Density (P/Km²), Urban Pop %, Urban Population, Country's Share of World Pop, World Population, Pakistan Global Rank]
Index: []